name: Build DLL (Linux) (MSVC)

# Workaround because the MinGW one causes crashes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel sudo git cmake extra-cmake-modules python wine msitools ca-certificates libwbclient

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          cd ~
          git clone https://github.com/mstorsjo/msvc-wine
          cd msvc-wine
          ./vsdownload.py --dest ~/my_msvc --accept-license
          ./install.sh ~/my_msvc/opt/msvc
          cd ..
          export PATH=~/my_msvc/opt/msvc/bin/x64:$PATH
          CC=cl CXX=cl cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Windows
          make
          EOF

      - name: Upload artifact/s
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: |
            build-gg/dinput8.dll
