name: Build Launcher (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel sudo git cmake extra-cmake-modules mingw-w64-binutils mingw-w64-crt mingw-w64-gcc mingw-w64-headers mingw-w64-winpthreads

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          cd Launcher
          mkdir build-launcher
          cd build-launcher
          sh -c "
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake
          "
          cmake --build .
          EOF

      - name: Upload artifact/s
        uses: actions/upload-artifact@v4
        with:
          name: Launcher
          path: |
            Launcher/build-launcher/GardenGate_Launcher.exe
